
package com.java.src;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IllegalInputException", targetNamespace = "http://com.src/")
public class IllegalInputException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private IllegalInputException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IllegalInputException_Exception(String message, IllegalInputException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IllegalInputException_Exception(String message, IllegalInputException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: src.com.IllegalInputException
     */
    public IllegalInputException getFaultInfo() {
        return faultInfo;
    }

}
