
package com.java.src;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalog", targetNamespace = "http://com.src/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalog {


    /**
     * 
     * @param inputParam
     * @return
     *     returns java.lang.String
     * @throws IllegalInputException_Exception
     */
    @WebMethod
    @WebResult(name = "OutputParam", partName = "OutputParam")
    @Action(input = "http://com.src/ProductCatalog/getProductNameRequest", output = "http://com.src/ProductCatalog/getProductNameResponse", fault = {
        @FaultAction(className = IllegalInputException_Exception.class, value = "http://com.src/ProductCatalog/getProductName/Fault/IllegalInputException")
    })
    public String getProductName(
        @WebParam(name = "InputParam", partName = "InputParam")
        int inputParam)
        throws IllegalInputException_Exception
    ;

    /**
     * 
     * @return
     *     returns src.com.ArrayList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://com.src/ProductCatalog/getAllProductsRequest", output = "http://com.src/ProductCatalog/getAllProductsResponse")
    public ArrayList getAllProducts();

    /**
     * 
     * @return
     *     returns src.com.ArrayList
     */
    @WebMethod
    @WebResult(name = "Product", partName = "Product")
    @Action(input = "http://com.src/ProductCatalog/getAllProductRequest", output = "http://com.src/ProductCatalog/getAllProductResponse")
    public ArrayList getAllProduct();

}
